### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by metya** [alexzh2/SimpleSwitcher#3]
Есть возможность сделать версию для Linux?

**Comment by alexzh2** [comment]
Нет, для linux нужно делать полностью отдельную программу. Кроме того из-за постоянного разброда и шатаний в линуксе реализовать все не так то просто. Как минимум нужны разные версии под X и Wayland. Я линуксом пользуюсь редко и разбираться во всем этом банально нет времени.

**Comment by metya** [comment]
Понял, спасибо)
