### ISSUE TITLE
Смена раскладки набранного слова в строке поиска windows 10/11

### ISSUE THREAD

**Issue by nnmdd** [alexzh2/SimpleSwitcher#6]
Первичная смена раскладки всегда безуспешна, срабатывает всегда со второго раза, при это раскладку клавиатуры меняет оба раза, и в результате раскладка клавиатуры всегда не соответствует языку слова
![explorer_WiYuvEQEQH](https://user-images.githubusercontent.com/97770937/149681640-4c08b475-d119-40de-8827-4b9442c5bd9c.gif)
.

**Comment by alexzh2** [comment]
Добрый день! Да, такая проблема есть. Я как то пытался ее исправить, но так ничего и не вышло. Попробую как-нибудь еще раз, может получится.

**Comment by nnmdd** [comment]
Мне кажется достаточным исправлением было бы какое-то соотношение языка
ввода текста к раскладке, условно проверка успешности смены раскладки
только что введённого слова до смены раскладки клавиатуры, к тому что с
первого раза не срабатывает уже привык.
p.s. Спасибо за прогу, она делает всё что мне было нужно от пунтосвитчера
именно так, как мне было нужно, причём из коробки. пользуюсь уже несколько
лет, не могу нарадоваться.

пн, 17 янв. 2022 г. в 15:35, Alexsander ***@***.***>:

**Comment by alexzh2** [comment]
Вы правильно сказали - происходит рассинхронизация, язык еще не успевает смениться, а программа уже перенабирает текст. По хорошему, нужно добавить механизм ожидания подтвержения смены языка.

Рад что вам нравится, пользуйтесь на здоровье 😊. Я планирую и дальше развивать программу, хоть в последнее время почти ей не занимаюсь 🙉

**Comment by nnmdd** [comment]
[offtop] если есть куда вам отправить спасибо "на чай" - буду рад
возможности

вт, 18 янв. 2022 г. в 14:18, Alexsander ***@***.***>:

**Comment by alexzh2** [comment]
Я обновил главную страницу, добавил секцию Donate. Буду рад любой поддержке 🙂

**Comment by alexzh2** [comment]
Исправил эту ошибку в версии 3.0.0.8. Можете проверить.

**Comment by nnmdd** [comment]
спасибо, баг полностью ушёл. нашёл ещё один в другой функции, работающий крайне избирательно, но под него заведу отдельный тикет.

**Comment by nnmdd** [comment]
проверил, всё работает идеально,
